version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    resource_class: small
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: yarn install
            - run: yarn nx build server

workflows:
  build-and-test:
    jobs:
      - build-and-test
